### ISSUE TITLE
notFound handler blocks request to remote service

### ISSUE THREAD

**Issue by Flofie** [kalisio/feathers-distributed#18] opened 2018-12-13 15:07 UTC
If you activate the default express.notFound() handler of feathers this handler blocks the request to the remote services. You alway get a 404.
You could just remove the notFound Handler but the problem with that is that you then get a 404 and a html page returned. Since my client only accepts json we had a problem.

Here is my solution:
```javascript
// Configure a middleware for 404s and the error handler
app.use((req, res, next) => {
  if (app._router.stack.find(r => r.route && r.route.path && r.route.path === req.path)) {
    next();
  } else {
    const { url } = req;
    const message = `Page not found${process.env.NODE_ENV !== 'production' ? ': ' + url : ''}`;
    next(new NotFound(message, { url }));
  }
});
app.use(errorHandler);
```

Hope that helps.

**Comment by claustres** [comment] 2018-12-13 15:10
Duplicate of https://github.com/kalisio/feathers-distributed/issues/3 ? Maybe you should push your solution there.

**Comment by Flofie** [comment] 2018-12-13 15:12
good idea. Did that.

**Closed** 2018-12-13 15:13 UTC
