### ISSUE TITLE
Babel compile for target above NodeJS 10

### ISSUE THREAD

**Issue by dekelev** [kalisio/feathers-distributed#55] opened 2020-05-14 16:49 UTC
Due to some upgrades of babel modules in the _package-lock.json_ file, the `lib` directory now compiles to target above NodeJS 10, because NodeJS 10 doesn't support the `module.exports.default` property.

This results in requiring the module and accessing the `default` property in NodeJS 10: `const distributed = require('@kalisio/feathers-distributed').default`

_lib/index.js_ file seems to miss the line `module.exports = exports['default'];`

**Comment by claustres** [comment] 2020-05-14 17:04
I am not sure to understand the problem but as we mainly use yarn I am afraid we did not update the `package-lock.json` file correctly. I've just pushed a new one to master, could you check if it works better ?

Indeed the travis build under Node v10 seems to work fine but maybe it works well because it uses yarn as well or because of the way mocha is importing the package.

**Comment by dekelev** [comment] 2020-05-14 17:19
Didn't help. You can use the following test file to see the difference between v0.7.1 to v1.0.1:

test.js - place this in the root folder and run after running compile with `node test.js`:
```
const distributed = require('./lib');

console.log('typeof distributed:', typeof distributed);

// v1.0.1 - typeof distributed: object
// v0.7.1 - typeof distributed: function
```

**Comment by claustres** [comment] 2020-05-14 17:27
It seems to me adding `module.exports = exports['default']` is a workaround, there is probably something wrong with the code produced by babel following some changes although the `.babelrc` specify a Node v7 target. By the way we should probably increase the target for a more recent baseline.

Any help is welcome to find a "good" solution.

**Comment by dekelev** [comment] 2020-05-14 18:01
I might have time tomorrow to work this out. here's an example of such implementation: https://github.com/feathersjs-ecosystem/feathers-objection/blob/master/package.json

**Comment by claustres** [comment] 2020-05-14 19:28
As far as I understand the problem is linked to https://github.com/babel/babel/issues/2212 and that's the reason why https://www.npmjs.com/package/babel-plugin-add-module-exports should fix it. Except that we don't use the same babel versions it seems we use this plugin similarly so let's wait to your insight if you have a clearer vision of what to do to fix it, thanks.

**Comment by claustres** [comment] 2020-05-14 19:36
It might be related to https://www.npmjs.com/package/babel-plugin-add-module-exports#modules-false, however I am not completely sure of the consequences of changing this option.

**Comment by claustres** [comment] 2020-05-15 08:14
Just tried to add `modules: false` but then the code is not transpiled at all.

**Comment by dekelev** [comment] 2020-05-15 11:51
@claustres You just need to remove the other `export` keywords in _src/index.js_ file. leave only the main `export` on the init method, `export default function init (options = {}) {`, and run the `test.js` again to verify that you get a `function` type.

**Comment by dekelev** [comment] 2020-05-15 11:56
You can also add this Mocha test:

```
describe('Common Tests', () => {
    it('is CommonJS compatible', () =>
      assert.strictEqual(typeof require('../lib'), 'function'));
  });
```

**Comment by claustres** [comment] 2020-05-15 12:04
Should be fixed now, give it a try with your use case to see if it works then I will push a patch release.

Thanks for your support.

**Closed** 2020-05-15 12:04 UTC

**Comment by dekelev** [comment] 2020-05-15 12:07
Works perfect. Thanks!
