### ISSUE TITLE
Does not work with middleware

### ISSUE THREAD

**Issue by Flofie** [kalisio/feathers-distributed#13] opened 2018-10-05 12:28 UTC
Did you ever experience trouble with express middlewares?
I have a middleware registered on a service like:

` app.use(
    '/attachment',
    (req, res, next) => {
      next();
    },
    new AttachmentService({})
  );`

If I call the service directly via REST (http://localhost:4007/attachment) everything works fine. But I also registered the service with my Gateway via feathers-distributed but if I call the Gateway (http://localhost:4000/attachment) the request never reaches the service. More specific even the next() call within the middleware never gets called.
My guess is that the middleware somehow is making problems with the cote service call.

**Comment by claustres** [comment] 2018-10-05 14:56
This module performs "standard" Feathers services distribution and has not been tested with middleware. I guess the problem is [here](https://github.com/kalisio/feathers-distributed/blob/master/src/index.js#L88) because we simply support the single argument form of `app.use()`. A PR is welcome if you'd like to try to support the extended form with middleware like [here](https://github.com/feathersjs/feathers/blob/master/packages/express/lib/index.js#L27). I think it should work, that's only a matter of registering the service correctly in the module.

**Comment by claustres** [comment] 2019-06-08 21:44
Seems to be fixed on master according to tests, will release a new version soon with some enhancements.

**Closed** 2019-06-08 21:44 UTC
Labels: bug, help wanted
